Doc/diagrama_de_pacotes
UnBArqDsw2023-2/2023.2_G2_ProjetoAmazon pull request #36
Opened 2023-10-07 20:36 UTC by diogjunior100

2023-10-08 21:35 UTC, PedroLSF approved these changes

2023-10-09 02:05 UTC, gabrielm2q commented
- Diagrama de Pacotes: 
    - Adicionar subpacotes de Troca de Pontos e outro de Moderação no pacote de "Interface" 
    - No pacote de "Sistema de Avaliação", o subpacote "Recompensa" possui erro de digitação 
    - IDEIA: Tratar o Sistema de Troca de Pontos (Recompensa) como um pacote próprio, em paralelo ao pacote de "Sistema de Avaliação" e também acessando a base de dados 
    - IDEIA: Adicionar pacote de "Sistema de Moderação" como um pacote próprio, em paralelo ao pacote de "Sistema de Avaliação" e também acessando a base de dados, ligando-se ao pacote de "Sistema de Avaliação" e "Interface"

2023-10-09 02:06 UTC, gabrielm2q requested changes
- Diagrama de Pacotes: 
    - Adicionar subpacotes de Troca de Pontos e outro de Moderação no pacote de "Interface" 
    - No pacote de "Sistema de Avaliação", o subpacote "Recompensa" possui erro de digitação 
    - IDEIA: Tratar o Sistema de Troca de Pontos (Recompensa) como um pacote próprio, em paralelo ao pacote de "Sistema de Avaliação" e também acessando a base de dados 
    - IDEIA: Adicionar pacote de "Sistema de Moderação" como um pacote próprio, em paralelo ao pacote de "Sistema de Avaliação" e também acessando a base de dados, ligando-se ao pacote de "Sistema de Avaliação" e "Interface"

2023-10-09 22:40 UTC, gabrielm2q approved these changes

2023-10-09 22:40 UTC, merged